/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function keys_getShare(a: number, b: number, c: number): void;
export function keys_numShares(a: number): number;
export function keys_polynomial(a: number, b: number): void;
export function keys_thresholdPublicKey(a: number, b: number): void;
export function __wbg_keys_free(a: number): void;
export function __wbg_get_keys_t(a: number): number;
export function __wbg_set_keys_t(a: number, b: number): void;
export function __wbg_get_keys_n(a: number): number;
export function __wbg_set_keys_n(a: number, b: number): void;
export function keygen(a: number, b: number): number;
export function keypair_privateKey(a: number, b: number): void;
export function keypair_publicKey(a: number, b: number): void;
export function __wbg_keypair_free(a: number): void;
export function blindedmessage_message(a: number, b: number): void;
export function blindedmessage_blindingFactor(a: number, b: number): void;
export function __wbg_blindedmessage_free(a: number): void;
export function thresholdKeygen(a: number, b: number, c: number, d: number): number;
export function combine(a: number, b: number, c: number, d: number): void;
export function partialVerifyBlindSignature(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function partialVerify(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function partialSignBlindedMessage(a: number, b: number, c: number, d: number, e: number): void;
export function partialSign(a: number, b: number, c: number, d: number, e: number): void;
export function signBlindedMessage(a: number, b: number, c: number, d: number, e: number): void;
export function sign(a: number, b: number, c: number, d: number, e: number): void;
export function verifyBlindSignature(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function verify(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function unblind(a: number, b: number, c: number, d: number, e: number): void;
export function blind(a: number, b: number, c: number, d: number): number;
export function init(): void;
export function generate_private_key(a: number): number;
export function deserialize_private_key(a: number, b: number, c: number): number;
export function serialize_private_key(a: number, b: number, c: number): number;
export function private_key_to_public_key(a: number, b: number): number;
export function sign_message(a: number, b: number, c: number, d: number, e: number, f: number, g: number): number;
export function sign_pop(a: number, b: number, c: number, d: number): number;
export function hash_direct(a: number, b: number, c: number, d: number, e: number): number;
export function hash_composite(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function compress_signature(a: number, b: number, c: number, d: number): number;
export function compress_pubkey(a: number, b: number, c: number, d: number): number;
export function destroy_private_key(a: number): void;
export function free_vec(a: number, b: number): void;
export function destroy_public_key(a: number): void;
export function destroy_signature(a: number): void;
export function deserialize_public_key(a: number, b: number, c: number): number;
export function serialize_public_key(a: number, b: number, c: number): number;
export function deserialize_signature(a: number, b: number, c: number): number;
export function serialize_signature(a: number, b: number, c: number): number;
export function verify_signature(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): number;
export function batch_verify_signature(a: number, b: number, c: number, d: number): number;
export function verify_pop(a: number, b: number, c: number, d: number, e: number): number;
export function aggregate_public_keys(a: number, b: number, c: number): number;
export function aggregate_public_keys_subtract(a: number, b: number, c: number, d: number): number;
export function aggregate_signatures(a: number, b: number, c: number): number;
export function hash_test(a: number, b: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_malloc(a: number): number;
